### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Drxckzyz** [RaymondJiang1/anime-tracker#15]
Since discord introduced Message content intent, will this project be continued and will it be fully slash commands if so or do you plan to get the intent

**Comment by RaymondJiang1** [comment]
Probably will get the intent and add slash commands. Probs won't even make it public just a fun PrOjEcT

**Comment by Drxckzyz** [comment]
1. I RENAMED IT

2. Oop okie

**Comment by AMufInABox** [comment]
if this is anime tracker, is raymond an anime character?

**Comment by Drxckzyz** [comment]
What????

**Comment by AMufInABox** [comment]
hehe

**Comment by Drxckzyz** [comment]
d i e
